version: 2

## testing models Using dbt_utils Package
models:
  - name: stg_customer
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: "{{ref('customer_dim')}}"
    columns:
      - name: gender
        tests:
          - not_null
  
  

sources:
  - name: raw_data
    description: "Data From the Snow Flake Contains sales transcation and Customer Details"
    database: "{{target.database}}"
    schema: raw

    tables:
      - name: customer
        description: "Customer Details"
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: loaded_at_field

        columns:
          - name: CUSTOMERID
            description: "Primary key"
            tests:
              - not_null
              - unique

      - name: sale
        description: "Sales transactions from POS system"
        columns:
          - name: TRANSACTION_ID
            description: "Primary transaction ID"
            tests:
              - not_null
              - unique
          - name: CUSTOMER_ID
            description: "Foreign key to customer table"
            tests:
              - relationships:
                  to: source('raw_data', 'customer')
                  field: CUSTOMERID
          - name: GENDER
            description: "Gender of the customer"
          - name: unit_cost
            tests:
              - negative_values
